/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shha;

import javax.swing.JTable;
import static shha.mainGUI2.patientsContainerPanel;

/**
 *
 * @author Sheldon
 */
public class ChartTablePanel extends javax.swing.JPanel {

    /**
     * Creates new form ChartTablePanel
     */
    public ChartTablePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chartScollPane = new javax.swing.JScrollPane();
        chartTable = new javax.swing.JTable();
        testButton = new javax.swing.JButton();
        removeColButton = new javax.swing.JButton();

        chartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Sex", "Phone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        chartTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chartTableMouseClicked(evt);
            }
        });
        chartScollPane.setViewportView(chartTable);

        testButton.setText("Test");
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });

        removeColButton.setText("RmCol1");
        removeColButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeColButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeColButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(testButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chartScollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chartScollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(removeColButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chartTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chartTableMouseClicked
        if (evt.getClickCount() == 2) {
            JTable target = (JTable)evt.getSource();
            int row = target.getSelectedRow();
            int column = target.getSelectedColumn();
            System.out.println("Double Click on Row worked");

            patientsContainerPanel.removeAll();
            patientsContainerPanel.repaint();
            patientsContainerPanel.revalidate();

            ViewChartPanel viewChartPanel = new ViewChartPanel();

            patientsContainerPanel.add(viewChartPanel);
            patientsContainerPanel.repaint();
            patientsContainerPanel.revalidate();
        }
    }//GEN-LAST:event_chartTableMouseClicked

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed

    }//GEN-LAST:event_testButtonActionPerformed

    private void removeColButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeColButtonActionPerformed
        //        EmpTablePanel empTable = new EmpTablePanel();
        //        JTable table = empTable.getTable();
        //        table.removeColumn(table.getColumnModel().getColumn(0));
        //
        //        AbstractTableModel model = (AbstractTableModel)table.getModel();
        //        model.fireTableDataChanged();
        //        table.repaint();
        //        table.revalidate();
        //        empTable.repaint();
        //        empTable.revalidate();
        //
        //        empTablePanel.removeAll();
        //        empTablePanel.repaint();
        //        empTablePanel.revalidate();
        //
        //        empTablePanel.add(empTable);
        //        empTablePanel.repaint();
        //        empTablePanel.revalidate();
        //
        //        empContainerPanel.removeAll();
        //        empContainerPanel.repaint();
        //        empContainerPanel.revalidate();
        //
        //        empContainerPanel.add(empTablePanel);
        //        empContainerPanel.repaint();
        //        empContainerPanel.revalidate();
    }//GEN-LAST:event_removeColButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane chartScollPane;
    private javax.swing.JTable chartTable;
    private javax.swing.JButton removeColButton;
    private javax.swing.JButton testButton;
    // End of variables declaration//GEN-END:variables

    public JTable getTable(){
        return chartTable;
    }

}
