/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shha;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import static shha.mainGUI2.patientsContainerPanel;

/**
 *
 * @author Sheldon
 */
public class PatientTablePanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientTablePanel
     */
    public PatientTablePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientScollPane = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Sex", "Phone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        patientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientTableMouseClicked(evt);
            }
        });
        patientScollPane.setViewportView(patientTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientScollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientScollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void patientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientTableMouseClicked
        if (evt.getClickCount() == 2) {
            JTable target = (JTable)evt.getSource();
            int row = target.getSelectedRow();
            int column = target.getSelectedColumn();
            
            Database db = new Database("SMSDB2");
          /*  ResultSet rs = db.queryPatientInfo(patientTable.getValueAt(row, 5).toString());
            
            try {
                rs.next();
                ViewPatientPanel.firstNameText.setText(rs.getString(1));
                
            } catch(SQLException e) {
                
            } */

            patientsContainerPanel.removeAll();
            patientsContainerPanel.repaint();
            patientsContainerPanel.revalidate();

            ViewPatientPanel viewPatientPanel = new ViewPatientPanel();
            
            patientsContainerPanel.add(viewPatientPanel);
            patientsContainerPanel.repaint();
            patientsContainerPanel.revalidate();
        }
    }//GEN-LAST:event_patientTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane patientScollPane;
    private javax.swing.JTable patientTable;
    // End of variables declaration//GEN-END:variables

public JTable getTable(){
        return patientTable;
    }

}
