/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shha;

import javax.swing.ImageIcon;

/**
 *
 * @author Sheldon
 */
public class ViewChartPanel extends javax.swing.JPanel {

    /**
     * Creates new form chartPanel
     */
    public ViewChartPanel() {
        initComponents();
        
        java.net.URL imageURL = ViewChartPanel.class.getResource("/patient2.png");

    if (imageURL != null) {
        ImageIcon icon = new ImageIcon(imageURL);
      
        patientImage.setIcon(icon);
    }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContainerTabPane = new javax.swing.JTabbedPane();
        patientTabPane = new javax.swing.JTabbedPane();
        generalPanel = new javax.swing.JPanel();
        generalScrollPane = new javax.swing.JScrollPane();
        generalTextArea = new javax.swing.JTextArea();
        allergyPanel = new javax.swing.JPanel();
        allergyScrollPane = new javax.swing.JScrollPane();
        allergyTextArea = new javax.swing.JTextArea();
        medPanel = new javax.swing.JPanel();
        medScrollPane = new javax.swing.JScrollPane();
        medTextArea = new javax.swing.JTextArea();
        referredPanel = new javax.swing.JPanel();
        referredScrollPane = new javax.swing.JScrollPane();
        referredTextArea = new javax.swing.JTextArea();
        insurancePanel = new javax.swing.JPanel();
        insuranceScrollPane = new javax.swing.JScrollPane();
        insuranceTextArea = new javax.swing.JTextArea();
        visitPanel = new javax.swing.JPanel();
        visitScrollPane = new javax.swing.JScrollPane();
        visitTextArea = new javax.swing.JTextArea();
        chartTabPane = new javax.swing.JPanel();
        doctorTextField = new javax.swing.JTextField();
        doctorLabel = new javax.swing.JLabel();
        chartScrollPane = new javax.swing.JScrollPane();
        chartTextArea = new javax.swing.JTextArea();
        patientImage = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        hiddenSSNLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(991, 577));
        setMinimumSize(new java.awt.Dimension(991, 577));
        setPreferredSize(new java.awt.Dimension(991, 577));

        mainContainerTabPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainContainerTabPane.setMaximumSize(new java.awt.Dimension(991, 577));
        mainContainerTabPane.setMinimumSize(new java.awt.Dimension(991, 577));
        mainContainerTabPane.setPreferredSize(new java.awt.Dimension(991, 577));

        patientTabPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        generalTextArea.setColumns(20);
        generalTextArea.setRows(5);
        generalTextArea.setEnabled(false);
        generalScrollPane.setViewportView(generalTextArea);

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generalScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generalScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        patientTabPane.addTab("General", generalPanel);

        allergyTextArea.setColumns(20);
        allergyTextArea.setRows(5);
        allergyTextArea.setEnabled(false);
        allergyScrollPane.setViewportView(allergyTextArea);

        javax.swing.GroupLayout allergyPanelLayout = new javax.swing.GroupLayout(allergyPanel);
        allergyPanel.setLayout(allergyPanelLayout);
        allergyPanelLayout.setHorizontalGroup(
            allergyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allergyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allergyScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );
        allergyPanelLayout.setVerticalGroup(
            allergyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allergyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allergyScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        patientTabPane.addTab("Allergies", allergyPanel);

        medTextArea.setColumns(20);
        medTextArea.setRows(5);
        medTextArea.setEnabled(false);
        medScrollPane.setViewportView(medTextArea);

        javax.swing.GroupLayout medPanelLayout = new javax.swing.GroupLayout(medPanel);
        medPanel.setLayout(medPanelLayout);
        medPanelLayout.setHorizontalGroup(
            medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(medScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );
        medPanelLayout.setVerticalGroup(
            medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(medScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        patientTabPane.addTab("Routine Meds", medPanel);

        referredTextArea.setColumns(20);
        referredTextArea.setRows(5);
        referredTextArea.setEnabled(false);
        referredScrollPane.setViewportView(referredTextArea);

        javax.swing.GroupLayout referredPanelLayout = new javax.swing.GroupLayout(referredPanel);
        referredPanel.setLayout(referredPanelLayout);
        referredPanelLayout.setHorizontalGroup(
            referredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(referredPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(referredScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );
        referredPanelLayout.setVerticalGroup(
            referredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(referredPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(referredScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        patientTabPane.addTab("Referred By", referredPanel);

        insuranceTextArea.setColumns(20);
        insuranceTextArea.setRows(5);
        insuranceTextArea.setEnabled(false);
        insuranceScrollPane.setViewportView(insuranceTextArea);

        javax.swing.GroupLayout insurancePanelLayout = new javax.swing.GroupLayout(insurancePanel);
        insurancePanel.setLayout(insurancePanelLayout);
        insurancePanelLayout.setHorizontalGroup(
            insurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insurancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insuranceScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );
        insurancePanelLayout.setVerticalGroup(
            insurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insurancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insuranceScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        patientTabPane.addTab("Insurance", insurancePanel);

        visitTextArea.setColumns(20);
        visitTextArea.setRows(5);
        visitTextArea.setEnabled(false);
        visitScrollPane.setViewportView(visitTextArea);

        javax.swing.GroupLayout visitPanelLayout = new javax.swing.GroupLayout(visitPanel);
        visitPanel.setLayout(visitPanelLayout);
        visitPanelLayout.setHorizontalGroup(
            visitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(visitScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );
        visitPanelLayout.setVerticalGroup(
            visitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(visitScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        patientTabPane.addTab("Prior Visits", visitPanel);

        mainContainerTabPane.addTab("Patient", patientTabPane);

        doctorTextField.setEnabled(false);

        doctorLabel.setText("Doctor Name:");

        chartTextArea.setColumns(20);
        chartTextArea.setRows(5);
        chartTextArea.setEnabled(false);
        chartScrollPane.setViewportView(chartTextArea);

        javax.swing.GroupLayout chartTabPaneLayout = new javax.swing.GroupLayout(chartTabPane);
        chartTabPane.setLayout(chartTabPaneLayout);
        chartTabPaneLayout.setHorizontalGroup(
            chartTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartTabPaneLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(chartTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chartScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(chartTabPaneLayout.createSequentialGroup()
                        .addComponent(doctorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doctorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        chartTabPaneLayout.setVerticalGroup(
            chartTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartTabPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chartTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorLabel))
                .addGap(18, 18, 18)
                .addComponent(chartScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        mainContainerTabPane.addTab("Chart Notes", chartTabPane);

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Thomas Jeffereson");

        saveButton.setText("Save");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        messageLabel.setForeground(java.awt.Color.red);
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        hiddenSSNLabel.setText("Hidden");
        hiddenSSNLabel.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(patientImage, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 59, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hiddenSSNLabel)
                        .addGap(112, 112, 112)))
                .addComponent(mainContainerTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {editButton, saveButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainContainerTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(patientImage, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hiddenSSNLabel)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {editButton, saveButton});

    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        saveButton.setEnabled(true);
        editButton.setEnabled(false);
        messageLabel.setText("");
        
        generalTextArea.setEnabled(true);
        allergyTextArea.setEnabled(true);
        medTextArea.setEnabled(true);
        referredTextArea.setEnabled(true);
        insuranceTextArea.setEnabled(true);
        visitTextArea.setEnabled(true);
        doctorTextField.setEnabled(true);
        chartTextArea.setEnabled(true);
        
        
    }//GEN-LAST:event_editButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        editButton.setEnabled(true);
        saveButton.setEnabled(false);
        messageLabel.setText("Changes Have Been Saved!");
        
        generalTextArea.setEnabled(false);
        allergyTextArea.setEnabled(false);
        medTextArea.setEnabled(false);
        referredTextArea.setEnabled(false);
        insuranceTextArea.setEnabled(false);
        visitTextArea.setEnabled(false);
        doctorTextField.setEnabled(false);
        chartTextArea.setEnabled(false);
        
        Database db = new Database("SMSDB2");
        String query= "UPDATE patient_chart SET " +
                        "general='" + generalTextArea.getText() +"', "  +
                        "allergies='" + allergyTextArea.getText() + "', " +
                        "rountine_meds='" + medTextArea.getText() + "', " +
                        "reffered_by='" + referredTextArea.getText() + "', " +
                        "insurance='" + insuranceTextArea.getText() + "', " +
                        "prior_visits='" + visitTextArea.getText() + "', " +
                        "doctor='" + doctorTextField.getText() + "', " +
                        "chart='" + chartTextArea.getText()  +"' " +
                        "WHERE patient_ssn='" + hiddenSSNLabel.getText() +"'";
        db.executePatientUpdate(query);         
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allergyPanel;
    private javax.swing.JScrollPane allergyScrollPane;
    public static javax.swing.JTextArea allergyTextArea;
    private javax.swing.JScrollPane chartScrollPane;
    private javax.swing.JPanel chartTabPane;
    public static javax.swing.JTextArea chartTextArea;
    private javax.swing.JLabel doctorLabel;
    public static javax.swing.JTextField doctorTextField;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JScrollPane generalScrollPane;
    public static javax.swing.JTextArea generalTextArea;
    public static javax.swing.JLabel hiddenSSNLabel;
    private javax.swing.JPanel insurancePanel;
    private javax.swing.JScrollPane insuranceScrollPane;
    public static javax.swing.JTextArea insuranceTextArea;
    private javax.swing.JTabbedPane mainContainerTabPane;
    private javax.swing.JPanel medPanel;
    private javax.swing.JScrollPane medScrollPane;
    public static javax.swing.JTextArea medTextArea;
    private javax.swing.JLabel messageLabel;
    public static javax.swing.JLabel nameLabel;
    private javax.swing.JLabel patientImage;
    private javax.swing.JTabbedPane patientTabPane;
    private javax.swing.JPanel referredPanel;
    private javax.swing.JScrollPane referredScrollPane;
    public static javax.swing.JTextArea referredTextArea;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel visitPanel;
    private javax.swing.JScrollPane visitScrollPane;
    public static javax.swing.JTextArea visitTextArea;
    // End of variables declaration//GEN-END:variables



}
